package contacts.exceptions;

import java.util.Map;

@SuppressWarnings({"WeakerAccess", "unused"})
public class ErrorInfo {

  public final int status;
  public final String message;
  public final String url;
  public final Map<String, String[]> params;

  /**
   * Constructor.
   *
   * @param status  the http response status being sent
   * @param message the message generated by the exception
   * @param url     the requests URL
   * @param params  query parameters sent with the URL
   */
  public ErrorInfo(int status, String message, String url, Map<String, String[]> params) {
    this.status = status;
    this.message = message;
    this.url = url;
    this.params = params;
  }

}
